CREATE TABLE TGVCUS (
    CODCUS BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CUSNAME VARCHAR(255) NOT NULL,
    CUSADDR VARCHAR(255) NOT NULL,
    CUSCITY VARCHAR(255) NOT NULL,
    CUSSTATE VARCHAR(255) NOT NULL,
    CUSZIP VARCHAR(20) NOT NULL,
    CUSPHONE VARCHAR(20) NOT NULL,
    CUSEMAIL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
)