CREATE TABLE TGVEXP (
    CODEXP BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    EXPDESC VARCHAR(255) NOT NULL,
    EXPCOST INTEGER NOT NULL,
    EXPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPTYPE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255) NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE

)