CREATE TABLE TGVORD (
    CODORD BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ORDCOST_IN_CENTS INTEGER NOT NULL,
    CODCUS BIGINT NOT NULL,
    ORDSTS VARCHAR(25) NOT NULL,
    ORDPAYTYPE VARCHAR(20),
    ORDPAYDUE DATE NOT NULL,
    ORDNOTE VARCHAR(255),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CONSTRAINT fk_tgvord_customer FOREIGN KEY (codcus)
        REFERENCES TGVCUS (codcus)
);