CREATE TABLE TGVITE (
    CODITE BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CODORD BIGINT NOT NULL,
    CODPROD BIGINT NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE_IN_CENTS INTEGER NOT NULL,
    DISCOUNT_PRECENT REAL,
    TOTAL_IN_CENTS INTEGER NOT NULL,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    CONSTRAINT fk_tgvite_order FOREIGN KEY (codord)
        REFERENCES TGVORD (codord),
    CONSTRAINT fk_tgvite_product FOREIGN KEY (codprod)
        REFERENCES TGVSTO (codprod)
);