CREATE TABLE TGVLOG (
    CODLOG BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ENTITY VARCHAR(50) NOT NULL,
    ENTITY_ID BIGINT NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    FIELD VARCHAR(50),
    OLD_VALUE VARCHAR(255),
    NEW_VALUE VARCHAR(255),
    CHANGED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);