ALTER TABLE tgvuse
    add column IS_DELETED BOOLEAN DEFAULT FALSE,
    add column CREATED_BY VARCHAR(255),
    add column UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    add column UPDATED_BY VARCHAR(255);
